### ISSUE TITLE
github webhooks seem to be broken

### ISSUE THREAD

**Issue by willwh** [Lullabot/lubot#40]
SyntaxError: Unexpected token u
    at Object.parse (native)
    at /home/willwh/lullabot/lubot/scripts/github.js:9:26
    at callbacks (/home/willwh/lullabot/lubot/node_modules/express/lib/router/index.js:164:37)
    at param (/home/willwh/lullabot/lubot/node_modules/express/lib/router/index.js:138:11)
    at pass (/home/willwh/lullabot/lubot/node_modules/express/lib/router/index.js:145:5)
    at Router._dispatch (/home/willwh/lullabot/lubot/node_modules/express/lib/router/index.js:173:5)
    at Object.router (/home/willwh/lullabot/lubot/node_modules/express/lib/router/index.js:33:10)
    at next (/home/willwh/lullabot/lubot/node_modules/express/node_modules/connect/lib/proto.js:193:15)
    at Object.urlencoded [as handle](/home/willwh/lullabot/lubot/node_modules/express/node_modules/connect/lib/middleware/urlencoded.js:38:27)
    at next (/home/willwh/lullabot/lubot/node_modules/express/node_modules/connect/lib/proto.js:193:15)

**Comment by willwh** [comment]
We shouldn't be JSON.parse() req.body :)
